# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -s $GITHUB_WORKSPACE/a/WWV/WWV/.github/workflows/maven-settings.xml -B package --file pom.xml 
        env:
          USER_NAME: ${{ secrets.USER_NAME }}
          ACCESS_TOKEN: ${{ secrets.TOKEN }}
      - name: Create release
        id: create_release
        run: |
          set -xe
          RELDATE="$(date +'%Y-%m-%d %H:%M')"
          NAME="Auto-Build $RELDATE"
          TAGNAME="autobuild-$(date +'%Y-%m-%d-%H-%M')"
          hub release create $(for a in target/*.jar; do echo -a $a; done) -m "$NAME" -t "main" "$TAGNAME"
        env:
          GITHUB_TOKEN: ${{ github.token }}
