# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
on:
  pull_request:
    tags:
      - "v*.*"
  workflow_dispatch:

name: Upload Release Asset
jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: /target/WeirdWelprVideo-*.jar
